import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
       <div
  className="
    font-sans min-h-screen 
    bg-[url('/events.jpg')] bg-no-repeat bg-center bg-cover 
    sm:bg-cover md:bg-fixed 
    grid place-items-center p-4 sm:p-8 md:p-12 lg:p-20
  "
>
  <main
    className="p-6 sm:p-8 md:p-8 text-center bg-white/70 rounded-2xl shadow-lg 
               w-full max-w-3xl"
  >
    {children}
  </main>
</div>

      </body>
    </html>
  );
}

